spring:
  application:
    name: dt2influx

management:
  influx:
    metrics:
      export:
        auto-create-db: false
        api-version: v1
        enabled: false
  dynatrace:
    metrics:
      export:
        enabled: false
  prometheus:
    metrics:
      export:
        enabled: false
  datadog:
    metrics:
      export:
        enabled: false
  appoptics:
    metrics:
      export:
        enabled: false
  atlas:
    metrics:
      export:
        enabled: false

env:
  influx:
    url: "http://localhost:8686"
    user: "admin"
    pass: "admin"
    database: "mydb"
    batch_size: 1000
    batch_interval_ms: 3000000

  reflex:
    url: "https://reflex/port/dddd"
    token: " Api-Token dt-c12312312"
    period: "30m"
    interval: 5

