spring:
  application:
    name: dt2influx

server:
  port: 8080

env:
  influx:
    url: "http://localhost:8686"
    user: "admin"
    pass: "admin"
    database: "mydb"
    batch_size: 1000
    batch_interval_ms: 3000000
    retention_policy: "base_ret"

  reflex:
    url: "https://reflex/port/dddd"
    token: " Api-Token dt-c12312312"
    period: "30m"
    interval: 300

